services:

  node1:
    image: reveries-network
    expose:
      - "9001"
    ports:
      - "9901:9901"
      - "9001:9001"
    stdin_open: true
    tty: true
    restart: always
    networks:
      - p2p-net
    command: >
      sh -c 'ls && cargo run --bin rpc -- \
        --secret-key-seed 1 \
        --rpc-port 9901 \
        --listen-address "/ip4/0.0.0.0/tcp/9001" \
        --bootstrap-peers "/dns4/node2/tcp/9002/p2p/12D3KooWH3uVF6wv47WnArKHk5p6cvgCJEb74UTmxztmQDc298L3"
        '
    ## note bootstrap-peers in docker uses /dns4/node2, not /ip4/127.0.0.1

  node2:
    image: reveries-network
    expose:
      - "9002"
    ports:
      - "9902:9902"
      - "9002:9002"
    restart: always
    stdin_open: true
    tty: true
    networks:
      - p2p-net
    command: >
      sh -c 'sleep 1 && cargo run --bin rpc -- \
        --secret-key-seed 2 \
        --rpc-port 9902 \
        --listen-address "/ip4/0.0.0.0/tcp/9002" \
        --bootstrap-peers "/dns4/node1/tcp/9001/p2p/12D3KooWPjceQrSwdWXPyLLeABRXmuqt69Rg3sBYbU1Nft9HyQ6X"
        '

  node3:
    image: reveries-network
    expose:
      - "9003"
    ports:
      - "9903:9903"
      - "9003:9003"
    restart: always
    stdin_open: true
    tty: true
    networks:
      - p2p-net
    command: >
      sh -c 'sleep 2 && cargo run --bin rpc -- \
        --secret-key-seed 3 \
        --rpc-port 9903 \
        --listen-address "/ip4/0.0.0.0/tcp/9003" \
        --bootstrap-peers "/dns4/node1/tcp/9001/p2p/12D3KooWPjceQrSwdWXPyLLeABRXmuqt69Rg3sBYbU1Nft9HyQ6X"
      '

  node4:
    image: reveries-network
    expose:
      - "9004"
    ports:
      - "9904:9904"
      - "9004:9004"
    restart: always
    stdin_open: true
    tty: true
    networks:
      - p2p-net
    command: >
      sh -c 'sleep 4 && cargo run --bin rpc -- \
        --secret-key-seed 4 \
        --rpc-port 9904 \
        --listen-address "/ip4/0.0.0.0/tcp/9004" \
        --bootstrap-peers "/dns4/node1/tcp/9001/p2p/12D3KooWPjceQrSwdWXPyLLeABRXmuqt69Rg3sBYbU1Nft9HyQ6X"
      '

  node5:
    image: reveries-network
    expose:
      - "9005"
    ports:
      - "9905:9905"
      - "9005:9005"
    restart: always
    stdin_open: true
    tty: true
    networks:
      - p2p-net
    command: >
      sh -c 'sleep 6 && cargo run --bin rpc -- \
        --secret-key-seed 5 \
        --rpc-port 9905 \
        --listen-address "/ip4/0.0.0.0/tcp/9005" \
        --bootstrap-peers "/dns4/node1/tcp/9001/p2p/12D3KooWPjceQrSwdWXPyLLeABRXmuqt69Rg3sBYbU1Nft9HyQ6X"
      '

  node6:
    image: reveries-network
    expose:
      - "9006"
    ports:
      - "9906:9906"
      - "9006:9006"
    restart: always
    stdin_open: true
    tty: true
    networks:
      - p2p-net
    command: >
      sh -c 'sleep 6 && cargo run --bin rpc -- \
        --secret-key-seed 6 \
        --rpc-port 9906 \
        --listen-address "/ip4/0.0.0.0/tcp/9006" \
        --bootstrap-peers "/dns4/node1/tcp/9001/p2p/12D3KooWPjceQrSwdWXPyLLeABRXmuqt69Rg3sBYbU1Nft9HyQ6X"
      '

networks:
  p2p-net:
    driver: bridge