[package]
name = "llm-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
color-eyre = "0.6.3"
tracing = "0.1.41"
tracing-subscriber = "0.3"
regex = "1.10"
anyhow = "1.0"
once_cell = "1.9"
async-trait = "0.1"
http = "0.2"
hyper = { version = "0.14", features = ["full"] }
rcgen = "0.13"
rustls = "0.20"
tokio-rustls = "0.23"
rustls-pemfile = "1.0"
url = "2.4"
bytes = "1.5"
http-body-util = { version = "0.1.3", features = ["full"] }
webpki-roots = "0.22"
flate2 = "1.0"

# Add http-body and pin-project-lite for TeeBody implementation
http-body = "1.0"
pin-project-lite = "0.2"

# Add thiserror for custom errors
thiserror = "1.0"

# Add crates for ECDSA P-256
ecdsa = { version = "0.16", features = ["pem", "signing", "verifying"] }
p256 = { version = "0.13", features = ["ecdsa"] }
sha256 = "1.5"
rand_core = { version = "0.6", features = ["std"] } # For key generation

# Add signature crate
signature = { version = "2", features = ["std"] }
# Add sha2 crate
sha2 = "0.10"

# Add reqwest for sending reports
reqwest = { version = "0.12", features = ["json", "rustls-tls"] }

# Add base64 for encoding signature/payload
base64 = "0.22"

# Use hudsucker for MITM proxy
hudsucker = { version = "0.23", features = ["full"] }