services:

  ### TODO: configure router + port forwarding for
  ### NEAR inbound ports 24567
  nearcore-arm64:
    # image: nearprotocol/nearcore:latest
    image: nearcore-arm64
    container_name: nearcore-arm64
    build:
      context: . # Build context is the project root
      dockerfile: Dockerfile-neard # Path relative to context
    restart: unless-stopped
    volumes:
      - near_data_volume:/root/.near
    networks:
      - default     # Can be reached from host
    ports:
      - "3030:3030"  # RPC port
      - "24567:24567"  # Network port
    deploy: # Requires Docker Compose V2+
      resources:
        limits:
          memory: 26G # hits 24.5gb of memory
        reservations:
          memory: 8G
    memswap_limit: 28g

# Declare the named volume at the top level
volumes:
  near_data_volume:
    driver: local # Optional: specify driver (local is default)