FROM rust:latest AS builder

WORKDIR /usr/src/nearcore

RUN apt-get update && apt-get install -y cmake clang
RUN git clone https://github.com/near/nearcore .

# RUN cargo build -p neard --release
### TODO: Recompile with: RUN make neard
#   WARN: Running a neard executable which wasn't built with `make release` command isn't supported on mainnet.
#   WARN: Note that `cargo build --release` builds lack optimizations which may be needed to run properly on mainnet
#   WARN: Consider recompiling the binary using `make release` command.
RUN make neard

FROM debian:bookworm-slim

# Install runtime dependencies for neard, including libssl3
RUN apt-get update && apt-get install -y --no-install-recommends \
    libssl3 \
    ca-certificates \
    jq \
    iputils-ping \
    netcat-openbsd \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /usr/src/nearcore/target/release/neard /usr/local/bin/

# Copy the entrypoint script and make it executable
COPY ./near-node/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Set the entrypoint script as the command to run
ENTRYPOINT ["/entrypoint.sh"]

# Optionally, clear CMD if the base image defines one we don't need
# CMD []